**Pycaret 실습해보기**
* anaconda 설치 후 가상환경에서 실습 진행
* pycaret install 

```
$ pip install pycaret
```

In [1]:
#pycaret 
from pycaret.regression import *

In [2]:
#Loading Dataset
import seaborn as sns
dataset = sns.load_dataset('titanic')
dataset.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
#Train_Test split
from sklearn.model_selection import train_test_split
train_data, test_data = train_test_split(dataset, test_size = 0.3)

print(train_data.shape)
print(test_data.shape)

(623, 15)
(268, 15)

In [4]:
#Data preprocessing & Create Pipeline
ixi_model = setup(session_id=1, data=train_data, target='age', test_data= test_data, use_gpu=True, n_jobs=10, remove_perfect_collinearity = True)

# 각 컬럼에 Type을 표시 -> 맞을 경우 Enter, 지금까지의 내용에 대한 요약
# 선택한 옵션은 초록색으로 표시

In [5]:
models()  # 사용 가능한 모델

[LightGBM] [Fatal] GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1
[LightGBM] [Fatal] CUDA Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_CUDA=1

,Name,Reference,Turbo
ID,,,
lr,Linear Regression,sklearn.linear_model._base.LinearRegression,True
lasso,Lasso Regression,sklearn.linear_model._coordinate_descent.Lasso,True
ridge,Ridge Regression,sklearn.linear_model._ridge.Ridge,True
en,Elastic Net,sklearn.linear_model._coordinate_descent.Elast...,True
lar,Least Angle Regression,sklearn.linear_model._least_angle.Lars,True
llar,Lasso Least Angle Regression,sklearn.linear_model._least_angle.LassoLars,True
omp,Orthogonal Matching Pursuit,sklearn.linear_model._omp.OrthogonalMatchingPu...,True
br,Bayesian Ridge,sklearn.linear_model._bayes.BayesianRidge,True
ard,Automatic Relevance Determination,sklearn.linear_model._bayes.ARDRegression,False
par,Passive Aggressive Regressor,sklearn.linear_model._passive_aggressive.Passi...,True
ransac,Random Sample Consensus,sklearn.linear_model._ransac.RANSACRegressor,False
tr,TheilSen Regressor,sklearn.linear_model._theil_sen.TheilSenRegressor,False
huber,Huber Regressor,sklearn.linear_model._huber.HuberRegressor,True
kr,Kernel Ridge,sklearn.kernel_ridge.KernelRidge,False
svm,Support Vector Regression,sklearn.svm._classes.SVR,False
knn,K Neighbors Regressor,sklearn.neighbors._regression.KNeighborsRegressor,True
dt,Decision Tree Regressor,sklearn.tree._classes.DecisionTreeRegressor,True
rf,Random Forest Regressor,sklearn.ensemble._forest.RandomForestRegressor,True
et,Extra Trees Regressor,sklearn.ensemble._forest.ExtraTreesRegressor,True
ada,AdaBoost Regressor,sklearn.ensemble._weight_boosting.AdaBoostRegr...,True
gbr,Gradient Boosting Regressor,sklearn.ensemble._gb.GradientBoostingRegressor,True
mlp,MLP Regressor,sklearn.neural_network._multilayer_perceptron....,False
lightgbm,Light Gradient Boosting Machine,lightgbm.sklearn.LGBMRegressor,True
dummy,Dummy Regressor,sklearn.dummy.DummyRegressor,True

모델 적용해보기

In [6]:
# Model Conpare
pycaret_regression_models = compare_models(n_select = 2, sort = "MAE", include = ["lr","lasso","ridge","en","lar","llar","omp","rf"])

#좋은 성능을 보이는 부분을 노란색으로 표시

In [7]:
pycaret_regression_models

#best model에 대한 정보

[Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
       normalize=False, random_state=1, solver='auto', tol=0.001),
 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=10, normalize=False)]

In [8]:
best_model = create_model('ridge')

In [9]:
#tunning 
from sklearn.linear_model import *

#defualt_lasso_model = Lasso()
tuned_model = tune_model(best_model, n_iter= 100,optimize ="MAE")

In [10]:
tuned_model

#파라미터 값이 변경된 것을 알 수 있음

Ridge(alpha=5.07, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=1, solver='auto', tol=0.001)

In [11]:
#save best model

save_model(tuned_model, './best_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[], ml_usecase='regression',
                                       numerical_features=[], target='age',
                                       time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical=None,
                                 fill_value_numerical=None,
                                 numeric_strategy='me...
                 ('dummy', Dummify(target='age')),
                 ('fix_perfect', Remove_100(target='age')),
                 ('clean_names', Clean_Colum_Names()),
                 ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                 ('dfs', 'passthrough'), ('pca', 'passthrough'),
                 ['trained_model',
                  Ridge(alpha=5.07, copy_X=True, fit_intercept=True,
                        max_iter=None, normalize=False, random_state=1,
                        solver='auto', tol=0.001)]],
          verbose=False),
 './best_model.pkl')

In [12]:
#Load model

load_model = load_model('./best_model')

Transformation Pipeline and Model Successfully Loaded

In [13]:
load_model['trained_model']

Ridge(alpha=5.07, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=1, solver='auto', tol=0.001)